INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Glenna Horn','lobortis.risus.in@aol.edu','974-9332 Sodales Ave','Canada'),
  ('Dai Jimenez','tristique@outlook.ca','Ap #735-5438 Sapien, St.','Brazil'),
  ('Blossom Vasquez','aenean.massa.integer@hotmail.couk','Ap #909-8564 Nec Rd.','France'),
  ('Bruno Lang','bibendum.sed.est@yahoo.com','421-7838 Mollis St.','New Zealand'),
  ('Kane Sargent','vel.sapien@outlook.edu','Ap #359-9894 Ut, Av.','Belgium'),
  ('Tasha Barry','orci.tincidunt@hotmail.net','3913 Elementum Rd.','Italy'),
  ('Shoshana Moran','libero.nec@hotmail.org','Ap #487-6896 Elit Ave','Indonesia'),
  ('Jena Byrd','urna.et@protonmail.ca','868-8878 Aptent Av.','Sweden'),
  ('Hasad Brown','felis.eget@icloud.ca','137-2054 Sit Rd.','Spain'),
  ('Carl Marks','tellus.phasellus@hotmail.ca','256-7305 Ac St.','United States'),
  ('Aphrodite Mullins','vel@yahoo.ca','7918 Ullamcorper, St.','France'),
  ('Clinton Church','duis.ac@aol.ca','P.O. Box 983, 2058 Etiam Av.','Norway'),
  ('Magee Blair','tincidunt.nibh@icloud.ca','322-9889 Sed St.','Mexico'),
  ('Rahim Taylor','et.lacinia.vitae@aol.net','Ap #256-1716 Per Street','India'),
  ('Mechelle Bernard','euismod@google.org','P.O. Box 272, 727 Congue. Rd.','Singapore'),
  ('Emerson Stevenson','eu.placerat@outlook.com','908-5294 At Av.','Singapore'),
  ('Kirestin Baxter','vitae.erat.vivamus@icloud.couk','519-735 Enim Avenue','Belgium'),
  ('Flynn Kemp','eget.metus@icloud.net','461-3012 Amet Av.','New Zealand'),
  ('Xantha Richard','donec.dignissim.magna@hotmail.couk','508-5991 In Avenue','Poland'),
  ('Cade Faulkner','vulputate@aol.ca','Ap #408-3904 Viverra. St.','Belgium'),
  ('Tad Hewitt','consequat.lectus.sit@icloud.edu','699-5003 Non Ave','Chile'),
  ('Chadwick Rogers','arcu.vestibulum@google.couk','2541 Dolor St.','Philippines');
INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Serena Melendez','elit.etiam.laoreet@yahoo.org','539-8516 Dolor. Avenue','Chile'),
  ('Megan Weber','adipiscing.fringilla.porttitor@icloud.org','793-1028 Non, Rd.','Colombia'),
  ('Sharon Armstrong','eget.laoreet@icloud.couk','159-8897 Laoreet Rd.','Italy'),
  ('Libby Buckley','libero.lacus@hotmail.ca','3744 Maecenas Av.','Ireland'),
  ('Rhoda Juarez','adipiscing@outlook.org','Ap #956-5754 Lorem Avenue','Nigeria'),
  ('Kay Weber','ornare@icloud.org','Ap #218-9311 Tristique St.','United States'),
  ('Inez Terrell','eget.ipsum@hotmail.net','P.O. Box 266, 3407 Nascetur Road','Chile'),
  ('Samson Reilly','lacus.cras@google.ca','620-5079 Eu, Rd.','Italy'),
  ('Kelsie Hodge','id.nunc@protonmail.com','P.O. Box 241, 7831 Pellentesque Ave','Vietnam'),
  ('Ira King','integer.urna@protonmail.edu','5714 Massa. St.','South Korea'),
  ('Rana Perez','eleifend@yahoo.org','Ap #275-7124 Vitae St.','Spain'),
  ('Jonah Burnett','scelerisque.scelerisque@google.com','384-648 Massa. Street','Russian Federation'),
  ('Vladimir Carter','vivamus.rhoncus@hotmail.com','Ap #678-805 Nulla Rd.','Nigeria'),
  ('Rana Burton','consectetuer.mauris@hotmail.net','P.O. Box 430, 3169 Donec Rd.','Canada'),
  ('Preston Mcdowell','gravida.aliquam@icloud.net','495-6135 Ut Road','Australia'),
  ('Brielle Farmer','quis@yahoo.com','829-6650 Nec Street','Belgium'),
  ('Victor Richardson','ac.mattis.ornare@protonmail.net','Ap #301-218 Cras Road','Mexico'),
  ('Jaime Chase','metus.vivamus.euismod@google.edu','Ap #444-1910 Dictum. Street','China'),
  ('Wallace Guzman','ipsum.ac.mi@protonmail.org','4553 Et, Rd.','Ireland'),
  ('Sonia Porter','a.nunc@yahoo.org','1929 Tempor Rd.','Norway'),
  ('Kimberly Guzman','posuere.at.velit@outlook.couk','520-6691 Arcu. St.','Canada'),
  ('Madeson Hubbard','cras@aol.com','Ap #850-5030 Lobortis Ave','Poland');
INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Donna Pennington','consectetuer.adipiscing@google.edu','708-1627 Interdum Av.','France'),
  ('Bert Tate','est.congue@icloud.edu','254-307 Lorem St.','Belgium'),
  ('Marny Hubbard','iaculis.odio@outlook.couk','354-3525 Semper St.','Norway'),
  ('Ivory Petty','vestibulum@outlook.ca','944-2307 Ipsum. Av.','New Zealand'),
  ('Jasper Kirby','lorem.luctus.ut@protonmail.org','P.O. Box 515, 2886 Metus. St.','Indonesia'),
  ('Keaton Hatfield','integer.id@aol.com','696-3396 Neque. Rd.','Italy');
INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Nero Kane','rhoncus@hotmail.org','9252 Duis St.','India'),
  ('Sigourney Chang','erat.sed@outlook.org','Ap #368-6236 Porttitor Street','Mexico'),
  ('Emi Key','et.tristique@aol.ca','179-1671 Phasellus Rd.','Spain'),
  ('Neil Lawrence','laoreet.libero@protonmail.net','Ap #467-2395 Aliquam St.','Pakistan'),
  ('Sonia Gonzalez','ridiculus.mus@yahoo.net','P.O. Box 782, 7232 Iaculis, Road','Ireland'),
  ('Kathleen Blanchard','non.lobortis@protonmail.edu','413-8064 Sem St.','India'),
  ('Ina Day','egestas.rhoncus.proin@icloud.org','768-9175 Est. Avenue','South Korea'),
  ('Alfonso Vega','sodales.elit@yahoo.couk','798-1775 Ante Ave','United Kingdom'),
  ('Walter Kelly','proin.ultrices@outlook.edu','306-1304 Donec Rd.','Indonesia'),
  ('Dexter Hubbard','semper@google.couk','Ap #411-3558 Sed Avenue','Netherlands'),
  ('Jessamine Gaines','fames.ac.turpis@protonmail.com','P.O. Box 762, 2839 Augue Street','Pakistan'),
  ('Amal Adams','dapibus.id@protonmail.com','Ap #585-8274 Semper Street','Pakistan'),
  ('Constance Carlson','aliquam@icloud.edu','8199 Lectus Rd.','Nigeria'),
  ('Solomon Davis','quis@outlook.couk','3288 Vulputate Av.','United Kingdom'),
  ('Aline Morton','leo.cras@hotmail.edu','942-6888 Mi St.','Italy'),
  ('Dawn Rhodes','nec@aol.net','254-1169 Risus. St.','South Africa'),
  ('Elijah Williamson','curae.phasellus@protonmail.couk','Ap #828-2607 Ipsum St.','Pakistan'),
  ('Jin Prince','tincidunt@aol.com','415-159 Vitae Road','Canada'),
  ('Clarke Pena','a.auctor@outlook.com','Ap #537-4095 Ac Street','Austria'),
  ('Christen Kidd','consectetuer.rhoncus.nullam@icloud.com','P.O. Box 801, 4822 Sed Street','Philippines'),
  ('Indigo Glass','quis.accumsan.convallis@outlook.org','268-9503 Justo Rd.','Nigeria'),
  ('Vincent Guerrero','eu@yahoo.net','Ap #109-8073 Facilisis, Street','Pakistan');
INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Pascale Hudson','porttitor.scelerisque@icloud.net','8413 Donec Road','Brazil'),
  ('John Mitchell','et@google.edu','Ap #940-5019 Urna. Rd.','United Kingdom'),
  ('Arden Mcconnell','vitae@icloud.org','Ap #494-2740 Ligula Ave','Ukraine'),
  ('Virginia Ramos','iaculis@yahoo.com','Ap #677-1742 Mauris St.','Spain'),
  ('Rama Mercado','diam@outlook.couk','Ap #412-7595 Tellus, Av.','Poland'),
  ('Kenneth Valenzuela','risus.varius@google.net','Ap #812-9781 Vivamus Street','India'),
  ('Mariko Camacho','pede.cum.sociis@aol.net','2365 Iaculis Road','South Korea'),
  ('Dawn Copeland','tellus.sem@protonmail.org','Ap #752-6348 Et Avenue','Belgium'),
  ('Justine Stout','erat.eget@outlook.com','P.O. Box 226, 904 Non, Av.','Brazil'),
  ('Owen Mcmillan','aliquet.metus@aol.ca','364-2359 Ultricies Ave','Australia'),
  ('Chandler Wells','donec.feugiat@yahoo.com','Ap #521-7429 Tempus, Street','Pakistan'),
  ('Mason Berg','cras@aol.edu','814-9731 Placerat, Road','Chile'),
  ('Quin Bailey','cursus.vestibulum.mauris@protonmail.edu','Ap #984-590 Natoque Av.','China'),
  ('Maggie Barlow','nullam@google.org','161-8383 Sed Avenue','Spain'),
  ('Rachel Mccarthy','magna.sed.eu@hotmail.net','Ap #926-5962 Consectetuer Avenue','Philippines'),
  ('Carter Kirk','ac.ipsum@outlook.couk','Ap #901-9705 Consectetuer Rd.','Costa Rica'),
  ('Quon Reeves','dolor.sit@hotmail.edu','5438 Rhoncus. Av.','Singapore'),
  ('Jenette Kent','maecenas@hotmail.couk','606-3922 Interdum. Avenue','Vietnam'),
  ('Zahir Rodriguez','lectus.cum.sociis@aol.ca','Ap #580-920 Ligula. St.','Russian Federation'),
  ('Lev Perry','sed@protonmail.ca','471-5079 Tristique St.','Peru'),
  ('Elvis Burgess','aenean.eget@aol.ca','Ap #276-5491 Ut St.','Peru'),
  ('Gareth Brock','quis.accumsan@icloud.net','530-9411 Convallis Ave','South Africa');
INSERT INTO clientes (nome,email,endereco,pais)
VALUES
  ('Nash Wilkerson','nullam.vitae@protonmail.org','416-201 At, Street','Brazil'),
  ('Orla Gallagher','mattis@icloud.couk','P.O. Box 447, 9935 Tincidunt Street','Colombia'),
  ('Emma Craft','facilisis@protonmail.ca','Ap #590-6720 At Rd.','Mexico'),
  ('Rudyard Bowen','a@aol.couk','924-4461 Ultricies Ave','Norway'),
  ('Lee Malone','nunc.ac@aol.org','528-9911 Ac Ave','Belgium'),
  ('Ella Schwartz','iaculis.aliquet@icloud.com','184-1264 Ornare. Av.','Colombia');